#!/usr/bin/env python

import unittest
from tests import all_tests
from leaderboard import Leaderboard

if __name__ == "__main__":
    tests = all_tests()
    results = unittest.TextTestRunner().run(tests)
